dev:
  apt:
    - libxml2-dev
    - libxslt1-dev

  pip:
    - check-manifest
    - coverage
    - detox
    - fmap
    - lxml
    - nose
    - pip-tools
    - Sphinx
    - twine
    - tox
    - xunitmerge

prod:
  pip:
    - docker
    - syn>=0.0.14
    - syn.utils